import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router';
import { ArrowRight, HelpCircle } from 'lucide-react';
import { useLearningPath } from '../hooks/useLearningPath.js';
import { useUpdateSkill } from '../hooks/useUpdateSkill.js';
import { LEVEL_NAMES } from '../components/ui/LevelPicker.jsx';
import { getReasonLabel } from '../utils/reasonLabels.js';
import { Card, Tag, Button, LevelPicker, Skeleton, ErrorState, EmptyState } from '../components/ui';

/**
 * Learning Path page (/app/path).
 * Vertical timeline of prerequisite-ordered curriculum steps with
 * inline proficiency updates and AI explanations.
 */
export default function LearningPath({ career }) {
  useEffect(() => {
    document.title = 'SkillGraph — Learning Path';
  }, []);

  const navigate = useNavigate();
  const [showAll, setShowAll] = useState(false);
  const { data, isLoading, isError, error, refetch } = useLearningPath(career);
  const updateSkillMutation = useUpdateSkill();

  const totalSteps = data?.totalSteps ?? data?.steps?.length ?? 0;
  const totalEffortPoints = data?.totalEffortPoints ?? 0;
  const steps = data?.steps || [];
  const visibleSteps = showAll ? steps : steps.slice(0, 6);

  if (isLoading) {
    return (
      <div data-testid="path-skeleton" className="p-4 md:p-8 max-w-4xl mx-auto space-y-6 font-sans">
        <Skeleton variant="card" height={100} />
        <div className="space-y-4">
          <Skeleton variant="card" height={130} />
          <Skeleton variant="card" height={130} />
          <Skeleton variant="card" height={130} />
        </div>
      </div>
    );
  }

  if (isError) {
    return (
      <div className="p-6 md:p-12 font-sans flex items-center justify-center min-h-[500px]">
        <ErrorState
          title="FAILED TO LOAD LEARNING PATH"
          message={error?.message || 'Could not fetch your personalized curriculum.'}
          onRetry={refetch}
        />
      </div>
    );
  }

  if (steps.length === 0) {
    return (
      <div className="p-6 md:p-12 font-sans flex items-center justify-center min-h-[500px]">
        <EmptyState
          title="NO LEARNING STEPS"
          text="You have no remaining gaps for this target career, or no target career has been selected."
        />
      </div>
    );
  }

  return (
    <div className="p-4 md:p-8 max-w-4xl mx-auto font-sans flex flex-col gap-6">
      {/* Header Card */}
      <header className="bg-surface border-2 border-ink shadow-md p-6">
        <div className="flex flex-wrap items-center justify-between gap-3 mb-2">
          <Tag tone="brand">{data?.career?.name || 'Target Career'}</Tag>
          <span className="font-mono text-xs font-bold uppercase tracking-wider text-muted">
            {totalSteps} steps - {totalEffortPoints} effort points
          </span>
        </div>
        <h1 className="font-display uppercase text-2xl md:text-3xl tracking-tight text-ink">
          ORDERED LEARNING PATH
        </h1>
        <p className="text-sm text-muted font-sans mt-1">
          Topologically ordered prerequisite sequence generated by our deterministic rule engine.
        </p>
      </header>

      {/* Vertical Timeline of Step Cards */}
      <div className="space-y-4">
        {visibleSteps.map((step) => {
          const neededPrereqs = (step.prerequisites || [])
            .map((p) => p.name || p.slug)
            .join(', ');

          return (
            <Card key={step.order} tone="default" className="relative p-5">
              <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
                {/* Left: Step Order & Skill Info */}
                <div className="space-y-2 flex-1">
                  <div className="flex items-center gap-3">
                    <span className="font-display text-2xl text-brand leading-none">
                      {String(step.order).padStart(2, '0')}
                    </span>
                    <h2 className="font-display uppercase text-lg text-ink">
                      {step.skill?.name}
                    </h2>
                    <Tag tone="default">{step.skill?.category}</Tag>
                    {step.isReadyNow ? (
                      <Tag tone="pop">READY NOW</Tag>
                    ) : (
                      <span className="text-xs font-mono text-muted">
                        Needs: {neededPrereqs || 'Prerequisites'}
                      </span>
                    )}
                  </div>

                  {/* Level Transitions & Effort */}
                  <div className="flex flex-wrap items-center gap-2 pt-1">
                    <span className="px-2 py-0.5 border border-ink bg-paper font-mono text-xs font-bold">
                      Lv {step.fromLevel} ({LEVEL_NAMES[step.fromLevel]})
                    </span>
                    <ArrowRight size={14} className="text-muted" />
                    <span className="px-2 py-0.5 border border-ink bg-surface font-mono text-xs font-bold text-brand">
                      Lv {step.toLevel} ({LEVEL_NAMES[step.toLevel]})
                    </span>
                    <span className="px-2 py-0.5 border border-line bg-paper font-mono text-xs text-muted">
                      {step.effortPoints} pts
                    </span>
                  </div>

                  {/* Reason Tags */}
                  {step.reasons?.length > 0 && (
                    <div className="flex flex-wrap gap-1.5 pt-1">
                      {step.reasons.map((code) => (
                        <Tag key={code} tone="soft" className="text-[10px]">
                          {getReasonLabel(code)}
                        </Tag>
                      ))}
                    </div>
                  )}
                </div>

                {/* Right: Actions */}
                <div className="flex flex-col sm:items-end gap-3 shrink-0 pt-2 sm:pt-0 border-t sm:border-t-0 border-line">
                  <div className="flex items-center gap-2">
                    <span className="font-mono text-xs text-muted font-bold">I&apos;m now at:</span>
                    <LevelPicker
                      value={step.fromLevel}
                      onChange={(newLevel) => {
                        updateSkillMutation.mutate({
                          skillSlug: step.skill?.slug,
                          proficiency: newLevel,
                        });
                      }}
                      compact
                      disabled={updateSkillMutation.isPending}
                    />
                  </div>

                  <Button
                    size="sm"
                    variant="secondary"
                    icon={<HelpCircle size={14} />}
                    onClick={() => {
                      const query = encodeURIComponent(`Why should I learn ${step.skill?.name}?`);
                      navigate(`/app/assistant?q=${query}`);
                    }}
                    className="text-xs h-7 px-2.5"
                  >
                    Ask why
                  </Button>
                </div>
              </div>
            </Card>
          );
        })}
      </div>

      {/* Show All Steps Toggle */}
      {steps.length > 6 && (
        <div className="text-center pt-2">
          <Button
            variant="secondary"
            size="md"
            onClick={() => setShowAll(!showAll)}
            className="font-mono text-xs uppercase"
          >
            {showAll ? 'Show fewer steps' : `Show all ${steps.length} steps`}
          </Button>
        </div>
      )}
    </div>
  );
}
